### ISSUE TITLE
Feat : 프로필 기능 만들기 시작

### ISSUE THREAD

**Issue by ssujinchoi** [deverymarkit/deverymarkit#51]
## 🪄요구사항
yourProfile, myProfile기능 만들기
![스크린샷 2022-12-20 오전 10 09 21](https://user-images.githubusercontent.com/58455479/208557914-8097aa5c-4ba2-4a8c-b3f7-17f78dd53231.png)

## TODO
- [x] 가짜 json데이터 만든 후 axios로 데이터 가져오고 프로필, 상품목록, 게시글 보여주기
- [x] 앨범뷰 css
- [x] 게시글에서 게시글 정보(내용, 사진)를 누르면 게시글 상세보기로 이동하기
- [x] 게시글에서 유저 정보(사진, 이름 등)를 누르면 유저의 프로필로 이동하기
