### ISSUE TITLE
Refact : 게시글 관련 기능 보완

### ISSUE THREAD

**Issue by ssujinchoi** [deverymarkit/deverymarkit#71]
## 🪄TODO
- [x] 갤러리뷰에서 사진이 div밖으로 튀어나가는 현상 수정
- [x] 사진 여러장인거 슬라이드 기능추가
- [x] Date객체 써서 0000년xx월xx일로 포맷변환하기
- [x] 좋아요 기능 함수로 동작하게 수정
