### ISSUE TITLE
Refact : 프로필 관련 기능 수정

### ISSUE THREAD

**Issue by ssujinchoi** [deverymarkit/deverymarkit#76]
## 🪄 TODO
- [x] 프로필 수정/상품등록 navigate
- [x] 가격표시 콤마 찍어주기
- [x] 판매중인 상품 판매 url로 이동하기
- [x] 앨범뷰 사진 여러장일때 ‘여러장표시’ 아이콘 추가
